# BD
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: senha_secreta
    ports:
      - "5432:5432"

# JAVA
  backend:
    build: . # Caminho onde está o Dockerfile do Java
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: meu_usuario
      SPRING_DATASOURCE_PASSWORD: senha_secreta
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres